// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackTop: typeof import('./../src/components/BackTop/src/BackTop.vue')['default']
    ColorRadioPicker: typeof import('./../src/components/Setting/src/components/ColorRadioPicker.vue')['default']
    ConfigGlobal: typeof import('./../src/components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    ContentWrap: typeof import('./../src/components/ContentWrap/src/ContentWrap.vue')['default']
    ContextMenu: typeof import('./../src/components/ContextMenu/src/ContextMenu.vue')['default']
    Descriptions: typeof import('./../src/components/Descriptions/src/Descriptions.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./../src/components/Footer/src/Footer.vue')['default']
    Form: typeof import('./../src/components/Form/src/Form.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    Icon: typeof import('./../src/components/Icon/src/Icon.vue')['default']
    InputPassword: typeof import('./../src/components/InputPassword/src/InputPassword.vue')['default']
    InterfaceDisplay: typeof import('./../src/components/Setting/src/components/InterfaceDisplay.vue')['default']
    LayoutRadioPicker: typeof import('./../src/components/Setting/src/components/LayoutRadioPicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./../src/components/Screenfull/src/Screenfull.vue')['default']
    Search: typeof import('./../src/components/Search/src/Search.vue')['default']
    Setting: typeof import('./../src/components/Setting/src/Setting.vue')['default']
    SizeDropdown: typeof import('./../src/components/SizeDropdown/src/SizeDropdown.vue')['default']
    Table: typeof import('./../src/components/Table/src/Table.vue')['default']
    ThemeSwitch: typeof import('./../src/components/ThemeSwitch/src/ThemeSwitch.vue')['default']
    UserInfo: typeof import('./../src/components/UserInfo/src/UserInfo.vue')['default']
  }
}
